加入JavaScript callback功能
xresloader/xresloader pull request #24
Opened 2022-11-16 13:30 UTC by superwenda

1. 新增回调脚本处理单条配置的功能
2. 增加回调脚本示例

2022-11-17 01:47 UTC, owent commented
感谢提交，我这几天比较忙。过几天review完合入。

2022-11-21 05:27 UTC, owent commented
麻烦加一组新的测试而不是修改已有的？另外测试里可否也包含实际修改数据？
我需要能通过diff来确认已有流程的输出的兼容性。
新增的功能也需要后面至少能通过diff能确认没有破坏兼容性。

> 当然更好的是通过单元测试，不过目前验证流程还没写单元测试，每次更新完版本号会变。
> 但是至少需要能通过sample的输出人工也能检查兼容性。

2022-11-21 07:21 UTC, owent requested changes
有一些地方需要调整。另外麻烦新增一组sample而不是复用已有的，我们需要至少能够通过diff来确认没有破坏兼容性。
函数命名麻烦尽可能用完整名字不要用缩写，函数命名使用小写开头的驼峰。和大多数Java style保持一致。已有代码中有一些代码风格混乱的部分大多数是历史留存问题，以后会逐步改掉的。

2022-11-21 07:21 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +        if (lastDataSourceFile != DataSrcImpl.getOurInstance().getCurrentFileName()
`SchemeConf.getInstance().getCallbackScriptPath()` 变化是不是也需要重置？

2022-11-21 07:21 UTC, owent commented on src/org/xresloader/core/data/dst/DataDstJava.java
> +        if (DataETProcessor.getInstance().dumpMapMsg(ret, table.descriptor)) {
这里是不是也需要判定 `SchemeConf.getInstance().getCallbackScriptPath().isEmpty()` 走原来的方式？

2022-11-21 07:21 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +        boolean dumpSucceed = dumpMessage(builder, node);
`dumpSucceed` 返回 `false` 需要直接return掉？原先返回值是用来告诉上层是否有数据的。对不同的设置，可能会有不同的处理方式。或填充默认值，或裁剪。

2022-11-21 07:21 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +                val = obj.toString().getBytes();
这里需要处理一下，如果配置了 `SchemeConf.getInstance().getKey().getEncoding()` 需要按配置的编码转换。

2022-11-21 07:21 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +                Object curValue = src.get(fd.getName());
这里应该用 `getOrDefault(fd.getName(), null)`

2022-11-21 07:21 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +                                FillMap2Msg(fd.getMessageType(), (HashMap<String, Object>) arrItem, subMsgBuild);
这里可以用 instanceof `HashMap<String, ?>` 判断包一层，以抹除 `@SuppressWarnings("unchecked")` . 下同。

2022-11-21 07:21 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +                                if (mapItem.getValue() instanceof Map) {
这里最好通过pb的接口来判定是否是Message类型，这样能保证以后对特殊类型导出Map时，不会受到影响。

2022-11-21 07:21 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +                                    pushMapItem.setField(mapKVDesc.findFieldByName("key"), mapItem.getKey());
Key最好也过一下 `transformJava2Pb` 以防基类里对key类型做了特殊转换处理。

2022-11-21 07:21 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +    Object transformJava2Pb(FieldDescriptor fd, Object obj) {
这个接口转换数据前最好都判定一下源数据类型。不保证父类不会对一些特殊类型做一些特殊的转换。
比如：

+ 如果目标类型是整数，源类型是String，可以尝试类型转换。
+ 如果目标类型是Boolean，源类型是String，可以尝试调用 `DataSrcImpl.getBooleanFromString()` 转换内容。

2022-11-29 08:01 UTC, superwenda commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +                val = obj.toString().getBytes();
fixed

2022-11-29 08:06 UTC, superwenda commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +    Object transformJava2Pb(FieldDescriptor fd, Object obj) {
DataDstJava.dumpMessage已经将excel行转换为HashMap了，这里只是把数据填入DynamicMessage。如果js脚本填充了错误的数据到HashMap中，可考虑顺势在转换时抛出异常？

2022-11-29 08:07 UTC, superwenda commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +                val = obj.toString().getBytes();
后续添加修正

2022-11-30 06:42 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +    Object transformJava2Pb(FieldDescriptor fd, Object obj) {
因为之前pb数据转java内置数据是不保证类型一一对应的。特别是java没有unsigned类型。有些序列化库比如为了防止int64被自动转浮点丢失精度，会把它转成字符串表示。
目前没有转换但是也不保证未来一定会保证数据类型匹配。

2022-12-09 12:12 UTC, owent requested changes
最后还有2个小问题，麻烦再看一下？
另外问一下你合入dev不是rebase也不是merge的吗？
很奇怪我这里看到的这个PR和dev分支是分离的？

2022-12-09 12:12 UTC, owent commented on sample/gen_sample_output.ps1
> +        "-t js -p protobuf -o '$proto_dir'      -f '$proto_dir/kind.pb' --pretty 2 -m CallbackScript=none_cb.js -m 'DataSource=$XLSX_FILE|kind|3,1' -m 'MacroSource=$XLSX_FILE|macro|2,1' -m ProtoName=
有一些 `CallbackScript=none_cb.js` 漏清理了。

2022-12-09 12:12 UTC, owent commented on src/org/xresloader/core/data/et/DataETProcessor.java
> +                        pushMapItem.setField(mapKVDesc.findFieldByName("key"), mapItem.getKey());
Key最好也过一下 `transformJava2Pb` 以防基类里对key类型做了特殊转换处理。

2022-12-22 04:00 UTC, owent approved these changes

2022-12-22 04:00 UTC, owent commented
感谢贡献，本周得新冠请假了，下载处理。

2022-12-26 07:20 UTC, merged